//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public int Id { get; set; }
        public System.Guid OrderUniqueId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int LineQty { get; set; }
        public decimal LinePrice { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
